# Generated by Django 4.2.2 on 2023-09-21 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bangalo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImageBangalo', models.ImageField(upload_to='images/')),
                ('PlaceRestante', models.IntegerField(default=0, null=True)),
                ('ville', models.CharField(default='safi')),
            ],
        ),
        migrations.CreateModel(
            name='decouvrir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=150)),
                ('DecouvreImage', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='offrefield',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ImageDoffre', models.ImageField(upload_to='images/')),
                ('reduction', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Own_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.CharField(max_length=15000)),
                ('lmoursil', models.CharField(max_length=15000)),
                ('lmousta9bil', models.CharField(max_length=15000)),
                ('Message_RELATION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(default='images/B.jpg', null=True, upload_to='images/')),
                ('Image_RELATION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
